// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/build/re_type_definitions/rerun/blueprint/archetypes/card_layout.def.rs".

#pragma once

#include "../../blueprint/components/column_name.hpp"
#include "../../collection.hpp"
#include "../../component_batch.hpp"
#include "../../component_column.hpp"
#include "../../result.hpp"

#include <cstdint>
#include <optional>
#include <utility>
#include <vector>

namespace rerun::blueprint::archetypes {
    /// **Archetype**: Blueprint for displaying table records as cards.
    ///
    /// This archetype is stored at the entity `/table/layouts/cards`.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct CardLayout {
        /// The source column used for card titles.
        ///
        /// If unset, the first visible string column is used as the title.
        std::optional<ComponentBatch> title;

        /// The source column containing the target opened when a card is activated.
        ///
        /// If unset, the first configured preview field is used, then the first inferred URL column.
        std::optional<ComponentBatch> link;

        /// Source columns visible by default in each card, in display order.
        ///
        /// Unlisted fields are hidden unless their `archetypes::TableColumn` visibility overrides the default.
        /// Each source column may appear at most once.
        ///
        /// Fields with `TableCellKind::Flag` are omitted from the labeled-field list and the first one is shown in the card header.
        /// Card layouts currently support at most one flag field.
        std::optional<ComponentBatch> field_order;

      public:
        /// The name of the archetype as used in `ComponentDescriptor`s.
        static constexpr const char ArchetypeName[] = "rerun.blueprint.archetypes.CardLayout";

        /// `ComponentDescriptor` for the `title` field.
        static constexpr auto Descriptor_title = ComponentDescriptor(
            ArchetypeName, "CardLayout:title",
            Loggable<rerun::blueprint::components::ColumnName>::ComponentType
        );
        /// `ComponentDescriptor` for the `link` field.
        static constexpr auto Descriptor_link = ComponentDescriptor(
            ArchetypeName, "CardLayout:link",
            Loggable<rerun::blueprint::components::ColumnName>::ComponentType
        );
        /// `ComponentDescriptor` for the `field_order` field.
        static constexpr auto Descriptor_field_order = ComponentDescriptor(
            ArchetypeName, "CardLayout:field_order",
            Loggable<rerun::blueprint::components::ColumnName>::ComponentType
        );

      public:
        CardLayout() = default;
        CardLayout(CardLayout&& other) = default;
        CardLayout(const CardLayout& other) = default;
        CardLayout& operator=(const CardLayout& other) = default;
        CardLayout& operator=(CardLayout&& other) = default;

        explicit CardLayout(Collection<rerun::blueprint::components::ColumnName> _field_order)
            : field_order(
                  ComponentBatch::from_loggable(std::move(_field_order), Descriptor_field_order)
                      .value_or_throw()
              ) {}

        /// Update only some specific fields of a `CardLayout`.
        static CardLayout update_fields() {
            return CardLayout();
        }

        /// Clear all the fields of a `CardLayout`.
        static CardLayout clear_fields();

        /// The source column used for card titles.
        ///
        /// If unset, the first visible string column is used as the title.
        CardLayout with_title(const rerun::blueprint::components::ColumnName& _title) && {
            title = ComponentBatch::from_loggable(_title, Descriptor_title).value_or_throw();
            return std::move(*this);
        }

        /// The source column containing the target opened when a card is activated.
        ///
        /// If unset, the first configured preview field is used, then the first inferred URL column.
        CardLayout with_link(const rerun::blueprint::components::ColumnName& _link) && {
            link = ComponentBatch::from_loggable(_link, Descriptor_link).value_or_throw();
            return std::move(*this);
        }

        /// Source columns visible by default in each card, in display order.
        ///
        /// Unlisted fields are hidden unless their `archetypes::TableColumn` visibility overrides the default.
        /// Each source column may appear at most once.
        ///
        /// Fields with `TableCellKind::Flag` are omitted from the labeled-field list and the first one is shown in the card header.
        /// Card layouts currently support at most one flag field.
        CardLayout with_field_order(
            const Collection<rerun::blueprint::components::ColumnName>& _field_order
        ) && {
            field_order = ComponentBatch::from_loggable(_field_order, Descriptor_field_order)
                              .value_or_throw();
            return std::move(*this);
        }

        /// Partitions the component data into multiple sub-batches.
        ///
        /// Specifically, this transforms the existing `ComponentBatch` data into `ComponentColumn`s
        /// instead, via `ComponentBatch::partitioned`.
        ///
        /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
        ///
        /// The specified `lengths` must sum to the total length of the component batch.
        Collection<ComponentColumn> columns(const Collection<uint32_t>& lengths_);

        /// Partitions the component data into unit-length sub-batches.
        ///
        /// This is semantically similar to calling `columns` with `std::vector<uint32_t>(n, 1)`,
        /// where `n` is automatically guessed.
        Collection<ComponentColumn> columns();
    };

} // namespace rerun::blueprint::archetypes

namespace rerun {
    /// \private
    template <typename T>
    struct AsComponents;

    /// \private
    template <>
    struct AsComponents<blueprint::archetypes::CardLayout> {
        /// Serialize all set component batches.
        static Result<Collection<ComponentBatch>> as_batches(
            const blueprint::archetypes::CardLayout& archetype
        );
    };
} // namespace rerun
