// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_types/definitions/rerun/testing/components/fuzzy.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

#[doc(hidden)]
pub struct __AffixFuzzer20Marker;
pub type AffixFuzzer20 =
    crate::WrapperComponent<crate::testing::datatypes::AffixFuzzer20, __AffixFuzzer20Marker>;

#[allow(non_snake_case)]
#[inline]
pub const fn AffixFuzzer20(v: crate::testing::datatypes::AffixFuzzer20) -> AffixFuzzer20 {
    crate::WrapperComponent::<crate::testing::datatypes::AffixFuzzer20, __AffixFuzzer20Marker>(
        v,
        std::marker::PhantomData,
    )
}

impl ::re_types_core::Component for AffixFuzzer20 {
    #[inline]
    fn name() -> ComponentType {
        "rerun.testing.components.AffixFuzzer20".into()
    }
}

impl<T: Into<crate::testing::datatypes::AffixFuzzer20>> From<T> for AffixFuzzer20 {
    fn from(v: T) -> Self {
        AffixFuzzer20(v.into())
    }
}
