// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/build/re_type_definitions/rerun/testing/encodings/type_zoo.def.rs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::eq_op)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::arrow::array::ArrayRef;
use ::re_types_core::SerializationResult;
use ::re_types_core::SerializedComponentBatch;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};
use ::std::borrow::Cow;

/// **Encoding**: A fixed-size array of arrays — exercises nested fixed-size lists in Arrow.
#[derive(
    Clone,
    Debug,
    Default,
    Copy,
    PartialEq,
    bytemuck::Pod,
    bytemuck::Zeroable,
    ::re_byte_size::SizeBytes,
)]
#[repr(C)]
pub struct ManyVec3(pub [[f32; 3usize]; 2usize]);

::re_types_core::macros::impl_into_cow!(ManyVec3);

impl ::re_types_core::ArrowDatatype for ManyVec3 {
    #[inline]
    fn arrow_datatype() -> arrow::datatypes::DataType {
        use arrow::datatypes::*;
        DataType::FixedSizeList(
            std::sync::Arc::new(Field::new(
                "item",
                DataType::FixedSizeList(
                    std::sync::Arc::new(Field::new("item", DataType::Float32, false)),
                    3,
                ),
                false,
            )),
            2,
        )
    }
}

impl ::re_types_core::ToArrow for ManyVec3 {
    fn to_arrow<'a>(
        data: impl IntoIterator<Item = impl Into<Cow<'a, Self>>>,
    ) -> SerializationResult<ArrayRef>
    where
        Self: Clone + 'a,
    {
        #![allow(clippy::manual_is_variant_and)]
        use ::re_types_core::{
            ArrowDatatype as _, ResultExt as _, ToArrow as _, ToArrowOpt as _,
            arrow_helpers::as_array_ref,
        };
        use arrow::{array::*, buffer::*, datatypes::*};
        Ok({
            let data0: Vec<_> = data
                .into_iter()
                .map(|datum| {
                    let datum: Cow<'a, Self> = datum.into();
                    datum.into_owned().0
                })
                .collect();
            let data0_validity = None;
            {
                let data0_inner_data: Vec<_> = data0.into_iter().flatten().collect();
                let data0_inner_validity = None;
                as_array_ref(FixedSizeListArray::new(
                    std::sync::Arc::new(Field::new(
                        "item",
                        DataType::FixedSizeList(
                            std::sync::Arc::new(Field::new("item", DataType::Float32, false)),
                            3,
                        ),
                        false,
                    )),
                    2,
                    {
                        let data0_inner_data_inner_data: Vec<_> =
                            data0_inner_data.into_iter().flatten().collect();
                        let data0_inner_data_inner_validity = None;
                        as_array_ref(FixedSizeListArray::new(
                            std::sync::Arc::new(Field::new("item", DataType::Float32, false)),
                            3,
                            as_array_ref(PrimitiveArray::<Float32Type>::new(
                                data0_inner_data_inner_data.into_iter().collect(),
                                data0_inner_data_inner_validity,
                            )),
                            data0_inner_validity,
                        ))
                    },
                    data0_validity,
                ))
            }
        })
    }
}

impl ::re_types_core::FromArrow for ManyVec3 {
    #[inline]
    fn from_arrow(arrow_data: &dyn arrow::array::Array) -> DeserializationResult<Vec<Self>> {
        use ::re_types_core::{
            ArrowDatatype as _, FromArrow as _, FromArrowOpt as _, ResultExt as _,
            arrow_helpers::*, arrow_zip_validity::ZipValidity,
        };
        use arrow::{array::*, buffer::*, datatypes::*};
        err_on_nulls(arrow_data, "rerun.testing.encodings.ManyVec3")?;
        Ok({
            let slice = {
                let arrow_data = arrow_data
                    .try_cast::<arrow::array::FixedSizeListArray>(|| {
                        DataType::FixedSizeList(
                            std::sync::Arc::new(Field::new(
                                "item",
                                DataType::FixedSizeList(
                                    std::sync::Arc::new(Field::new(
                                        "item",
                                        DataType::Float32,
                                        false,
                                    )),
                                    3,
                                ),
                                false,
                            )),
                            2,
                        )
                    })
                    .with_context("rerun.testing.encodings.ManyVec3#triples")?;
                if arrow_data.value_length() != 2i32 {
                    return Err(DeserializationError::datatype_mismatch(
                        DataType::FixedSizeList(
                            std::sync::Arc::new(Field::new(
                                "item",
                                DataType::FixedSizeList(
                                    std::sync::Arc::new(Field::new(
                                        "item",
                                        DataType::Float32,
                                        false,
                                    )),
                                    3,
                                ),
                                false,
                            )),
                            2,
                        ),
                        arrow_data.data_type().clone(),
                    ))
                    .with_context("rerun.testing.encodings.ManyVec3#triples");
                }
                let arrow_data_inner = &**arrow_data.values();
                bytemuck::try_cast_slice::<_, [[f32; 3usize]; 2usize]>({
                    let arrow_data_inner = arrow_data_inner
                        .try_cast::<arrow::array::FixedSizeListArray>(|| {
                            DataType::FixedSizeList(
                                std::sync::Arc::new(Field::new("item", DataType::Float32, false)),
                                3,
                            )
                        })
                        .with_context("rerun.testing.encodings.ManyVec3#triples")?;
                    if arrow_data_inner.value_length() != 3i32 {
                        return Err(DeserializationError::datatype_mismatch(
                            DataType::FixedSizeList(
                                std::sync::Arc::new(Field::new("item", DataType::Float32, false)),
                                3,
                            ),
                            arrow_data_inner.data_type().clone(),
                        ))
                        .with_context("rerun.testing.encodings.ManyVec3#triples");
                    }
                    let arrow_data_inner_inner = &**arrow_data_inner.values();
                    bytemuck::try_cast_slice::<_, [f32; 3usize]>(
                        arrow_data_inner_inner
                            .try_cast::<Float32Array>(|| DataType::Float32)
                            .with_context("rerun.testing.encodings.ManyVec3#triples")?
                            .values()
                            .as_ref(),
                    )
                    .map_err(|err| DeserializationError::ValidationError(err.to_string()))
                    .with_context("rerun.testing.encodings.ManyVec3#triples")?
                })
                .map_err(|err| DeserializationError::ValidationError(err.to_string()))
                .with_context("rerun.testing.encodings.ManyVec3#triples")?
            };
            { slice.iter().copied().map(Self).collect::<Vec<_>>() }
        })
    }
}

impl From<[[f32; 3usize]; 2usize]> for ManyVec3 {
    #[inline]
    fn from(triples: [[f32; 3usize]; 2usize]) -> Self {
        Self(triples)
    }
}

impl From<ManyVec3> for [[f32; 3usize]; 2usize] {
    #[inline]
    fn from(value: ManyVec3) -> Self {
        value.0
    }
}
