# DO NOT EDIT!: This file was auto-generated by crates/re_types_builder/src/codegen/python.rs:277.

from __future__ import annotations

from typing import Sequence, Union

import pyarrow as pa
from attrs import define, field

from .._baseclasses import (
    BaseExtensionArray,
    BaseExtensionType,
)

__all__ = [
    "AnnotationContextIndicator",
    "AnnotationContextIndicatorArray",
    "AnnotationContextIndicatorArrayLike",
    "AnnotationContextIndicatorLike",
    "AnnotationContextIndicatorType",
]


@define
class AnnotationContextIndicator:
    """
    Indicator component for the `rerun.components.AnnotationContextIndicator` archetype.

    Indicator components are data-less components used to give some extra context.
    The Rerun Viewer can make use of them to provide better heuristics and even improve performance
    in some cases.
    """

    AnnotationContextIndicator: () = field(converter=())


AnnotationContextIndicatorLike = AnnotationContextIndicator
AnnotationContextIndicatorArrayLike = Union[
    AnnotationContextIndicator,
    Sequence[AnnotationContextIndicatorLike],
]


# --- Arrow support ---


class AnnotationContextIndicatorType(BaseExtensionType):
    def __init__(self) -> None:
        pa.ExtensionType.__init__(self, pa.null(), "rerun.components.AnnotationContextIndicator")


class AnnotationContextIndicatorArray(BaseExtensionArray[AnnotationContextIndicatorArrayLike]):
    _EXTENSION_NAME = "rerun.components.AnnotationContextIndicator"
    _EXTENSION_TYPE = AnnotationContextIndicatorType

    @staticmethod
    def _native_to_pa_array(data: AnnotationContextIndicatorArrayLike, data_type: pa.DataType) -> pa.Array:
        raise NotImplementedError  # You need to implement "annotationcontextindicator_native_to_pa_array" in rerun_py/rerun_sdk/rerun/_rerun2/components/_overrides/annotation_context_indicator.py


AnnotationContextIndicatorType._ARRAY_TYPE = AnnotationContextIndicatorArray

# TODO(cmc): bring back registration to pyarrow once legacy types are gone
# pa.register_extension_type(AnnotationContextIndicatorType())
