# NOTE: This file was autogenerated by re_types_builder; DO NOT EDIT.

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    BaseDelegatingExtensionArray,
    BaseDelegatingExtensionType,
)

__all__ = ["ClassIdArray", "ClassIdType"]


class ClassIdType(BaseDelegatingExtensionType):
    _TYPE_NAME = "rerun.components.ClassId"
    _DELEGATED_EXTENSION_TYPE = datatypes.ClassIdType


class ClassIdArray(BaseDelegatingExtensionArray[datatypes.ClassIdArrayLike]):
    _EXTENSION_NAME = "rerun.components.ClassId"
    _EXTENSION_TYPE = ClassIdType
    _DELEGATED_ARRAY_TYPE = datatypes.ClassIdArray


ClassIdType._ARRAY_TYPE = ClassIdArray

# TODO(cmc): bring back registration to pyarrow once legacy types are gone
# pa.register_extension_type(ClassIdType())
