RE_SDK_PYTHON := "crates/re_sdk_python"
PYTHON_BIN := "venv/bin"

## Set up virtual environment
venv:
    #!/usr/bin/env bash
    set -euxo pipefail
    python -m venv venv
    venv/bin/pip install --upgrade pip
    venv/bin/pip install -r requirements-build.txt
    venv/bin/pip install -r requirements-lint.txt
    unset CONDA_PREFIX && \
        source venv/bin/activate && \
        maturin develop

## Run autoformatting and linting
pre-commit: venv
	isort .
	black .
	blackdoc .
	pyupgrade --py37-plus `find examples/ rerun_sdk/ tests/ -name "*.py" -type f`
	mypy
	flake8
	cargo fmt --all

## Run fast unittests
test: venv
	#maturin develop
	python -m pytest tests/unit/

## Run all tests
test-all: venv
	maturin develop
	python -m pytest
	python tests/docs/run_doc_examples.py
