[package]
name = "test_gaussian_compare"
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true
version.workspace = true

[dependencies]
re_renderer.workspace = true
re_sdk_types = { workspace = true, features = ["default"] }
re_types_core.workspace = true

anyhow.workspace = true
clap.workspace = true
glam.workspace = true
image = { workspace = true, features = ["png"] }
macaw.workspace = true
pollster.workspace = true
wgpu.workspace = true

[lints]
workspace = true
