namespace rerun.blueprint.archetypes;

/// Configures spatial view properties.
table SpatialInformation (
    "attr.rerun.scope": "blueprint"
) {
  /// The target reference frame for all transformations.
  ///
  /// Defaults to the coordinate frame used by the space origin entity.
  target_frame: rerun.components.TransformFrameId ("attr.rerun.component_optional", order: 50);

  /// Whether the bounding box should be shown.
  // TODO(andreas): Make this an enum so the user can choose between showing bounding boxes,
  // regions of interest, or per-entity bounding boxes.
  show_bounding_box: rerun.blueprint.components.Enabled ("attr.rerun.component_optional", nullable, order: 100);

  /// Whether axes should be shown at the origin.
  show_axes: rerun.blueprint.components.Enabled ("attr.rerun.component_optional", nullable, order: 200);

  /// Controls the orientation of the axes in a 3D view; it has no effect in a 2D view.
  ///
  /// This determines the 3D eye orientation, navigation, and default grid plane.
  ///
  /// The three directions are always ordered as [x, y, z] and specify where each positive axis points.
  /// For example, [Right, Down, Forward] means that +X points right, +Y points down, and +Z points forward.
  ///
  /// When this property is unset, a 3D view first uses [archetypes.ViewCoordinates] logged at its origin entity or the closest ancestor.
  /// If none is found, it uses the camera orientation from the closest ancestor [archetypes.Pinhole].
  /// If neither is found, the fallback is RFU.
  ///
  /// This property is hidden from the selection panel for 2D views.
  ///
  /// ⚠ [Rerun does not yet support left-handed coordinate systems](https://github.com/rerun-io/rerun/issues/5032).
  // TODO(#1387): This property has no effect in 2D views and is hidden from its selection panel.
  axes: rerun.components.ViewCoordinates ("attr.rerun.component_optional", nullable, order: 300);
}
