namespace rerun.components;

// ---

/// Whether view-dependent color ([components.SphericalHarmonics3Rgb]) is used when rendering.
///
/// Disabling this in the blueprint can make the rendering a lot faster.
struct ShowSphericalHarmonics (
  "attr.arrow.transparent",
  "attr.docs.unreleased",
  "attr.python.aliases": "bool",
  "attr.python.array_aliases": "bool | npt.NDArray[np.bool_]",
  "attr.rerun.state": "unstable",
  "attr.rust.derive": "Copy, PartialEq, Eq",
  "attr.rust.tuple_struct"
) {
  /// Whether view-dependent color is evaluated.
  show_spherical_harmonics: rerun.datatypes.Bool (order: 100);
}
