namespace rerun.components;

// ---

/// View-dependent color, expressed as spherical harmonics coefficients of degrees 1 through 3.
///
/// The view-independent (degree-0) base color is represented as a separate [components.Color].
struct SphericalHarmonics3Rgb (
  "attr.docs.unreleased",
  "attr.rerun.state": "unstable",
  "attr.rust.derive": "Copy, PartialEq, bytemuck::Pod, bytemuck::Zeroable",
  "attr.rust.repr": "transparent"
) {
  coefficients: rerun.datatypes.SphericalHarmonics3Rgb (order: 100);
}
