namespace rerun.components;

/// An orientation convention for a camera or 3D view.
///
/// On [archetypes.Pinhole], this component controls the camera orientation and projection direction.
/// On [SpatialInformation](https://rerun.io/docs/reference/types/views/spatial3d_view), it controls the 3D view's eye orientation, navigation, and default grid plane.
/// A logged [archetypes.ViewCoordinates] provides the default for [SpatialInformation](https://rerun.io/docs/reference/types/views/spatial3d_view).
///
/// The three directions are always ordered as [x, y, z] and specify where each positive axis points.
/// For example, [Right, Down, Forward] means that +X points right, +Y points down, and +Z points forward.
///
/// ⚠ [Rerun does not yet support left-handed coordinate systems](https://github.com/rerun-io/rerun/issues/5032).
struct ViewCoordinates (
  "attr.cpp.no_field_ctors",
  "attr.python.aliases": "npt.ArrayLike",
  "attr.python.array_aliases": "npt.ArrayLike",
  "attr.rerun.state": "unstable",
  "attr.rust.derive": "Copy, PartialEq, Eq",
  "attr.rust.repr": "transparent"
) {
  /// The directions of the [x, y, z] axes.
  coordinates: rerun.datatypes.ViewCoordinates (order: 100);
}
