// DO NOT EDIT! This file was auto-generated by crates/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/re_types/definitions/rerun/archetypes/tensor.fbs".

#include "tensor.hpp"

#include "../indicator_component.hpp"

namespace rerun {
    namespace archetypes {
        const char Tensor::INDICATOR_COMPONENT_NAME[] = "rerun.components.TensorIndicator";

        Result<std::vector<SerializedComponentBatch>> Tensor::serialize() const {
            std::vector<SerializedComponentBatch> cells;
            cells.reserve(1);

            {
                auto result = ComponentBatch(data).serialize();
                RR_RETURN_NOT_OK(result.error);
                cells.emplace_back(std::move(result.value));
            }
            {
                components::IndicatorComponent<Tensor::INDICATOR_COMPONENT_NAME> indicator;
                auto result = ComponentBatch(indicator).serialize();
                RR_RETURN_NOT_OK(result.error);
                cells.emplace_back(std::move(result.value));
            }

            return cells;
        }
    } // namespace archetypes
} // namespace rerun
