# DO NOT EDIT! This file was auto-generated by crates/re_types_builder/src/codegen/python.rs
# Based on "crates/re_types/definitions/rerun/components/vector2d.fbs".

# You can extend this class by creating a "Vector2DExt" class in "vector2d_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import ComponentBatchMixin

__all__ = ["Vector2D", "Vector2DBatch", "Vector2DType"]


class Vector2D(datatypes.Vec2D):
    """**Component**: A vector in 2D space."""

    # You can define your own __init__ function as a member of Vector2DExt in vector2d_ext.py

    # Note: there are no fields here because Vector2D delegates to datatypes.Vec2D
    pass


class Vector2DType(datatypes.Vec2DType):
    _TYPE_NAME: str = "rerun.components.Vector2D"


class Vector2DBatch(datatypes.Vec2DBatch, ComponentBatchMixin):
    _ARROW_TYPE = Vector2DType()
