[package]
name = "custom_callback"
version = "0.39.0-alpha.3"
edition = "2024"
rust-version = "1.96"
license = "MIT OR Apache-2.0"
publish = false

[[bin]]
name = "custom_callback_viewer"
path = "src/viewer.rs"

[[bin]]
name = "custom_callback_app"
path = "src/app.rs"

[features]
default = []

# Turn on if you want to share analytics with Rerun (e.g. callstacks on crashes).
analytics = ["rerun/analytics"]

[dependencies]
rerun = { path = "../../../crates/top/rerun", default-features = false, features = [
  "native_viewer",
  "run",
  "server",
  "video",
  "log_setup",
] }

axum = { workspace = true, features = ["ws"] }
futures-util.workspace = true
mimalloc.workspace = true
parking_lot.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio = { workspace = true, features = [
  "macros",
  "net",
  "rt-multi-thread",
  "signal",
  "sync",
  "time",
] }
tokio-tungstenite.workspace = true

[target.'cfg(rerun_workspace_hack)'.dependencies]
re_workspace_hack.workspace = true
