// NOTE: This file was autogenerated by re_types_builder; DO NOT EDIT.
// Based on "crates/re_types/definitions/rerun/datatypes/rotation_axis_angle.fbs"

#pragma once

#include <cstdint>

#include "../datatypes/angle.hpp"
#include "../datatypes/vec3d.hpp"

namespace rr {
    namespace datatypes {
        struct RotationAxisAngle {
            rr::datatypes::Vec3D axis;
            rr::datatypes::Angle angle;
        };
    } // namespace datatypes
} // namespace rr
