#!/bin/sh

# This is a shim to call through to the managed pre-push hook.
# See: hooks/README.md for more details.
repo_root=$(git rev-parse --show-toplevel)
pre_push_hook=$repo_root/scripts/pre-push.sh
if [ -f "$pre_push_hook" ]; then
    exec $pre_push_hook
else
    echo "The pre-push hook appears to be missing from: $pre_push_hook -- Skipping."
    exit 0
fi
