// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/build/re_type_definitions/rerun/blueprint/components/column_name.def.rs".

#pragma once

#include "../../encodings/utf8.hpp"
#include "../../result.hpp"

#include <cstdint>
#include <memory>
#include <string>
#include <utility>

namespace rerun::blueprint::components {
    /// **Component**: The name of a column in a table.
    ///
    /// This is the physical column name: it is what the column is looked up by, and it is also
    /// what the user reads whenever the column has no separate, human-facing label.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct ColumnName {
        rerun::encodings::Utf8 value;

      public:
        ColumnName() = default;

        ColumnName(rerun::encodings::Utf8 value_) : value(std::move(value_)) {}

        ColumnName& operator=(rerun::encodings::Utf8 value_) {
            value = std::move(value_);
            return *this;
        }

        ColumnName(std::string value_) : value(std::move(value_)) {}

        ColumnName& operator=(std::string value_) {
            value = std::move(value_);
            return *this;
        }

        /// Cast to the underlying Utf8 encoding
        operator rerun::encodings::Utf8() const {
            return value;
        }
    };
} // namespace rerun::blueprint::components

namespace rerun {
    static_assert(sizeof(rerun::encodings::Utf8) == sizeof(blueprint::components::ColumnName));

    /// \private
    template <>
    struct Loggable<blueprint::components::ColumnName> {
        static constexpr std::string_view ComponentType = "rerun.blueprint.components.ColumnName";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::encodings::Utf8>::arrow_datatype();
        }

        /// Serializes an array of `rerun::blueprint:: components::ColumnName` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const blueprint::components::ColumnName* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::encodings::Utf8>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::encodings::Utf8>::to_arrow(&instances->value, num_instances);
            }
        }
    };
} // namespace rerun
