// DO NOT EDIT! This file was auto-generated by crates/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/re_types/definitions/rerun/blueprint/components/panel_expanded.fbs".

#include "panel_expanded.hpp"

#include <arrow/builder.h>

namespace rerun::blueprint::components {}

namespace rerun {}
