// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/blueprint/components/playback_speed.fbs".

#pragma once

#include "../../datatypes/float64.hpp"
#include "../../result.hpp"

#include <cstdint>
#include <memory>

namespace rerun::blueprint::components {
    /// **Component**: A playback speed which determines how fast time progresses.
    ///
    /// ⚠ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    ///
    struct PlaybackSpeed {
        /// 1.0 is default speed.
        rerun::datatypes::Float64 speed;

      public:
        PlaybackSpeed() = default;

        PlaybackSpeed(rerun::datatypes::Float64 speed_) : speed(speed_) {}

        PlaybackSpeed& operator=(rerun::datatypes::Float64 speed_) {
            speed = speed_;
            return *this;
        }

        PlaybackSpeed(double value_) : speed(value_) {}

        PlaybackSpeed& operator=(double value_) {
            speed = value_;
            return *this;
        }

        /// Cast to the underlying Float64 datatype
        operator rerun::datatypes::Float64() const {
            return speed;
        }
    };
} // namespace rerun::blueprint::components

namespace rerun {
    static_assert(
        sizeof(rerun::datatypes::Float64) == sizeof(blueprint::components::PlaybackSpeed)
    );

    /// \private
    template <>
    struct Loggable<blueprint::components::PlaybackSpeed> {
        static constexpr std::string_view ComponentType =
            "rerun.blueprint.components.PlaybackSpeed";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::datatypes::Float64>::arrow_datatype();
        }

        /// Serializes an array of `rerun::blueprint:: components::PlaybackSpeed` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const blueprint::components::PlaybackSpeed* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::datatypes::Float64>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::datatypes::Float64>::to_arrow(
                    &instances->speed,
                    num_instances
                );
            }
        }
    };
} // namespace rerun
