// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_sdk_types/definitions/rerun/archetypes/voxel_grid_map.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::allow_attributes)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::eq_op)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::wildcard_imports)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Archetype**: A sparse 3D voxel grid map with grid indices and voxel dimensions.
///
/// This archetype is intended for 3D occupancy maps and other volumetric data
/// represented as a sparse grid of voxels with scene-unit dimensions along the local X/Y/Z axes.
///
/// The minimum corner of the voxel with `[0, 0, 0]` index is located at the origin of the entity's coordinate frame
/// and can have an additional offset from there through the optional translation and rotation fields.
///
/// A voxel center is at `(index + 0.5) * voxel_size` in local grid coordinates (i.e. relative to the minimum corner).
///
/// ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
///
/// ## Example
///
/// ### Simple sparse voxel grid map
/// ```ignore
/// fn main() -> Result<(), Box<dyn std::error::Error>> {
///     let rec = rerun::RecordingStreamBuilder::new(
///         "rerun_example_voxel_grid_map_simple",
///     )
///     .spawn()?;
///
///     let voxel_indices = [
///         (-1, 0, 0),
///         (1, 0, 0),
///         (1, 1, 0),
///         (3, 0, 0),
///         (3, 0, 1),
///         (4, 0, 1),
///     ];
///     let values = [0.0_f32, 0.2, 0.4, 0.6, 0.8, 1.0];
///
///     rec.log(
///         "world/voxels",
///         &rerun::VoxelGridMap::new(voxel_indices, [0.25, 0.25, 0.25])
///             .with_values(values)
///             .with_value_range([0.0, 1.0])
///             .with_colormap(rerun::components::Colormap::Turbo)
///             .with_translation([-0.5, -0.5, 0.0]),
///     )?;
///
///     Ok(())
/// }
/// ```
#[derive(Clone, Debug, PartialEq, Default, ::re_byte_size::SizeBytes)]
pub struct VoxelGridMap {
    /// Indices of the voxels within the grid volume.
    pub voxel_indices: Option<SerializedComponentBatch>,

    /// The scene-unit dimensions of a single voxel cell.
    ///
    /// This defines the voxel size along the local grid X/Y/Z axes.
    /// Each dimension must be finite and positive.
    pub voxel_size: Option<SerializedComponentBatch>,

    /// Optional scalar occupancy or value data for each voxel.
    ///
    /// If explicit colors are not provided, values are mapped through `colormap` and `value_range`.
    pub values: Option<SerializedComponentBatch>,

    /// Optional colors for each voxel.
    ///
    /// If set, these colors take precedence over color-mapped scalar values.
    pub colors: Option<SerializedComponentBatch>,

    /// Translation of the minimum corner of voxel `[0, 0, 0]`.
    ///
    /// Together with [`components::RotationAxisAngle`][crate::components::RotationAxisAngle] or [`components::RotationQuat`][crate::components::RotationQuat], this defines the pose of the
    /// grid relative to the map's parent coordinate frame.
    ///
    /// If not set, the minimum corner is placed at the origin of the map's parent coordinate frame.
    pub translation: Option<SerializedComponentBatch>,

    /// Rotation of the grid via axis + angle.
    ///
    /// Together with [`components::Translation3D`][crate::components::Translation3D], this defines the pose of the grid relative to the
    /// map's parent coordinate frame.
    ///
    /// Note: either this or [`components::RotationQuat`][crate::components::RotationQuat] can be set to specify the grid's rotation, but not both.
    /// If both this and [`components::RotationQuat`][crate::components::RotationQuat] are set, this is ignored in favor of the quaternion.
    pub rotation_axis_angle: Option<SerializedComponentBatch>,

    /// Rotation of the grid via quaternion.
    ///
    /// Together with [`components::Translation3D`][crate::components::Translation3D], this defines the pose of the grid relative to the
    /// map's parent coordinate frame.
    pub quaternion: Option<SerializedComponentBatch>,

    /// Opacity of the voxels after color or colormap application.
    ///
    /// Defaults to 1.0 (fully opaque).
    pub opacity: Option<SerializedComponentBatch>,

    /// Scalar value range for color-mapping.
    ///
    /// Defaults to `[0.0, 1.0]`.
    pub value_range: Option<SerializedComponentBatch>,

    /// Colormap to use when `values` are present and explicit `colors` are not provided.
    ///
    /// Defaults to Turbo.
    pub colormap: Option<SerializedComponentBatch>,
}

impl VoxelGridMap {
    /// Returns the [`ComponentDescriptor`] for [`Self::voxel_indices`].
    ///
    /// The corresponding component is [`crate::components::VoxelIndex`].
    #[inline]
    pub fn descriptor_voxel_indices() -> ComponentDescriptor {
        static DESCRIPTOR: std::sync::LazyLock<ComponentDescriptor> =
            std::sync::LazyLock::new(|| ComponentDescriptor {
                archetype: Some("rerun.archetypes.VoxelGridMap".into()),
                component: "VoxelGridMap:voxel_indices".into(),
                component_type: Some("rerun.components.VoxelIndex".into()),
            });
        (*DESCRIPTOR).clone()
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::voxel_size`].
    ///
    /// The corresponding component is [`crate::components::VoxelSize`].
    #[inline]
    pub fn descriptor_voxel_size() -> ComponentDescriptor {
        static DESCRIPTOR: std::sync::LazyLock<ComponentDescriptor> =
            std::sync::LazyLock::new(|| ComponentDescriptor {
                archetype: Some("rerun.archetypes.VoxelGridMap".into()),
                component: "VoxelGridMap:voxel_size".into(),
                component_type: Some("rerun.components.VoxelSize".into()),
            });
        (*DESCRIPTOR).clone()
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::values`].
    ///
    /// The corresponding component is [`crate::components::VoxelValue`].
    #[inline]
    pub fn descriptor_values() -> ComponentDescriptor {
        static DESCRIPTOR: std::sync::LazyLock<ComponentDescriptor> =
            std::sync::LazyLock::new(|| ComponentDescriptor {
                archetype: Some("rerun.archetypes.VoxelGridMap".into()),
                component: "VoxelGridMap:values".into(),
                component_type: Some("rerun.components.VoxelValue".into()),
            });
        (*DESCRIPTOR).clone()
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::colors`].
    ///
    /// The corresponding component is [`crate::components::Color`].
    #[inline]
    pub fn descriptor_colors() -> ComponentDescriptor {
        static DESCRIPTOR: std::sync::LazyLock<ComponentDescriptor> =
            std::sync::LazyLock::new(|| ComponentDescriptor {
                archetype: Some("rerun.archetypes.VoxelGridMap".into()),
                component: "VoxelGridMap:colors".into(),
                component_type: Some("rerun.components.Color".into()),
            });
        (*DESCRIPTOR).clone()
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::translation`].
    ///
    /// The corresponding component is [`crate::components::Translation3D`].
    #[inline]
    pub fn descriptor_translation() -> ComponentDescriptor {
        static DESCRIPTOR: std::sync::LazyLock<ComponentDescriptor> =
            std::sync::LazyLock::new(|| ComponentDescriptor {
                archetype: Some("rerun.archetypes.VoxelGridMap".into()),
                component: "VoxelGridMap:translation".into(),
                component_type: Some("rerun.components.Translation3D".into()),
            });
        (*DESCRIPTOR).clone()
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::rotation_axis_angle`].
    ///
    /// The corresponding component is [`crate::components::RotationAxisAngle`].
    #[inline]
    pub fn descriptor_rotation_axis_angle() -> ComponentDescriptor {
        static DESCRIPTOR: std::sync::LazyLock<ComponentDescriptor> =
            std::sync::LazyLock::new(|| ComponentDescriptor {
                archetype: Some("rerun.archetypes.VoxelGridMap".into()),
                component: "VoxelGridMap:rotation_axis_angle".into(),
                component_type: Some("rerun.components.RotationAxisAngle".into()),
            });
        (*DESCRIPTOR).clone()
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::quaternion`].
    ///
    /// The corresponding component is [`crate::components::RotationQuat`].
    #[inline]
    pub fn descriptor_quaternion() -> ComponentDescriptor {
        static DESCRIPTOR: std::sync::LazyLock<ComponentDescriptor> =
            std::sync::LazyLock::new(|| ComponentDescriptor {
                archetype: Some("rerun.archetypes.VoxelGridMap".into()),
                component: "VoxelGridMap:quaternion".into(),
                component_type: Some("rerun.components.RotationQuat".into()),
            });
        (*DESCRIPTOR).clone()
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::opacity`].
    ///
    /// The corresponding component is [`crate::components::Opacity`].
    #[inline]
    pub fn descriptor_opacity() -> ComponentDescriptor {
        static DESCRIPTOR: std::sync::LazyLock<ComponentDescriptor> =
            std::sync::LazyLock::new(|| ComponentDescriptor {
                archetype: Some("rerun.archetypes.VoxelGridMap".into()),
                component: "VoxelGridMap:opacity".into(),
                component_type: Some("rerun.components.Opacity".into()),
            });
        (*DESCRIPTOR).clone()
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::value_range`].
    ///
    /// The corresponding component is [`crate::components::ValueRange`].
    #[inline]
    pub fn descriptor_value_range() -> ComponentDescriptor {
        static DESCRIPTOR: std::sync::LazyLock<ComponentDescriptor> =
            std::sync::LazyLock::new(|| ComponentDescriptor {
                archetype: Some("rerun.archetypes.VoxelGridMap".into()),
                component: "VoxelGridMap:value_range".into(),
                component_type: Some("rerun.components.ValueRange".into()),
            });
        (*DESCRIPTOR).clone()
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::colormap`].
    ///
    /// The corresponding component is [`crate::components::Colormap`].
    #[inline]
    pub fn descriptor_colormap() -> ComponentDescriptor {
        static DESCRIPTOR: std::sync::LazyLock<ComponentDescriptor> =
            std::sync::LazyLock::new(|| ComponentDescriptor {
                archetype: Some("rerun.archetypes.VoxelGridMap".into()),
                component: "VoxelGridMap:colormap".into(),
                component_type: Some("rerun.components.Colormap".into()),
            });
        (*DESCRIPTOR).clone()
    }
}

static REQUIRED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 2usize]> =
    std::sync::LazyLock::new(|| {
        [
            VoxelGridMap::descriptor_voxel_indices(),
            VoxelGridMap::descriptor_voxel_size(),
        ]
    });

static RECOMMENDED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 0usize]> =
    std::sync::LazyLock::new(|| []);

static OPTIONAL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 8usize]> =
    std::sync::LazyLock::new(|| {
        [
            VoxelGridMap::descriptor_values(),
            VoxelGridMap::descriptor_colors(),
            VoxelGridMap::descriptor_translation(),
            VoxelGridMap::descriptor_rotation_axis_angle(),
            VoxelGridMap::descriptor_quaternion(),
            VoxelGridMap::descriptor_opacity(),
            VoxelGridMap::descriptor_value_range(),
            VoxelGridMap::descriptor_colormap(),
        ]
    });

static ALL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 10usize]> =
    std::sync::LazyLock::new(|| {
        [
            VoxelGridMap::descriptor_voxel_indices(),
            VoxelGridMap::descriptor_voxel_size(),
            VoxelGridMap::descriptor_values(),
            VoxelGridMap::descriptor_colors(),
            VoxelGridMap::descriptor_translation(),
            VoxelGridMap::descriptor_rotation_axis_angle(),
            VoxelGridMap::descriptor_quaternion(),
            VoxelGridMap::descriptor_opacity(),
            VoxelGridMap::descriptor_value_range(),
            VoxelGridMap::descriptor_colormap(),
        ]
    });

impl VoxelGridMap {
    /// The total number of components in the archetype: 2 required, 0 recommended, 8 optional
    pub const NUM_COMPONENTS: usize = 10usize;
}

impl ::re_types_core::Archetype for VoxelGridMap {
    #[inline]
    fn name() -> ::re_types_core::ArchetypeName {
        ::re_types_core::external::re_string_interner::intern_static_nonempty!(
            ::re_types_core::ArchetypeName,
            "rerun.archetypes.VoxelGridMap"
        )
    }

    #[inline]
    fn display_name() -> &'static str {
        "Voxel grid map"
    }

    #[inline]
    fn required_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        REQUIRED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn recommended_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        RECOMMENDED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn optional_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        OPTIONAL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn all_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        ALL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn from_arrow_components(
        arrow_data: impl IntoIterator<Item = (ComponentDescriptor, arrow::array::ArrayRef)>,
    ) -> DeserializationResult<Self> {
        re_tracing::profile_function!();
        use ::re_types_core::{Loggable as _, ResultExt as _};
        let arrays_by_descr: ::nohash_hasher::IntMap<_, _> = arrow_data.into_iter().collect();
        let voxel_indices = arrays_by_descr
            .get(&Self::descriptor_voxel_indices())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_voxel_indices())
            });
        let voxel_size = arrays_by_descr
            .get(&Self::descriptor_voxel_size())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_voxel_size())
            });
        let values = arrays_by_descr
            .get(&Self::descriptor_values())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_values()));
        let colors = arrays_by_descr
            .get(&Self::descriptor_colors())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_colors()));
        let translation = arrays_by_descr
            .get(&Self::descriptor_translation())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_translation())
            });
        let rotation_axis_angle = arrays_by_descr
            .get(&Self::descriptor_rotation_axis_angle())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_rotation_axis_angle())
            });
        let quaternion = arrays_by_descr
            .get(&Self::descriptor_quaternion())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_quaternion())
            });
        let opacity = arrays_by_descr
            .get(&Self::descriptor_opacity())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_opacity()));
        let value_range = arrays_by_descr
            .get(&Self::descriptor_value_range())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_value_range())
            });
        let colormap = arrays_by_descr
            .get(&Self::descriptor_colormap())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_colormap()));
        Ok(Self {
            voxel_indices,
            voxel_size,
            values,
            colors,
            translation,
            rotation_axis_angle,
            quaternion,
            opacity,
            value_range,
            colormap,
        })
    }
}

impl ::re_types_core::AsComponents for VoxelGridMap {
    #[inline]
    fn as_serialized_batches(&self) -> Vec<SerializedComponentBatch> {
        use ::re_types_core::Archetype as _;
        [
            self.voxel_indices.clone(),
            self.voxel_size.clone(),
            self.values.clone(),
            self.colors.clone(),
            self.translation.clone(),
            self.rotation_axis_angle.clone(),
            self.quaternion.clone(),
            self.opacity.clone(),
            self.value_range.clone(),
            self.colormap.clone(),
        ]
        .into_iter()
        .flatten()
        .collect()
    }
}

impl ::re_types_core::ArchetypeReflectionMarker for VoxelGridMap {}

impl crate::VisualizableArchetype for VoxelGridMap {
    #[inline]
    fn visualizer(&self) -> crate::Visualizer {
        crate::Visualizer::new("VoxelGridMap").with_overrides(self)
    }
}

impl VoxelGridMap {
    /// Create a new `VoxelGridMap`.
    #[inline]
    pub fn new(
        voxel_indices: impl IntoIterator<Item = impl Into<crate::components::VoxelIndex>>,
        voxel_size: impl Into<crate::components::VoxelSize>,
    ) -> Self {
        Self {
            voxel_indices: try_serialize_field(Self::descriptor_voxel_indices(), voxel_indices),
            voxel_size: try_serialize_field(Self::descriptor_voxel_size(), [voxel_size]),
            values: None,
            colors: None,
            translation: None,
            rotation_axis_angle: None,
            quaternion: None,
            opacity: None,
            value_range: None,
            colormap: None,
        }
    }

    /// Update only some specific fields of a `VoxelGridMap`.
    #[inline]
    pub fn update_fields() -> Self {
        Self::default()
    }

    /// Clear all the fields of a `VoxelGridMap`.
    #[inline]
    pub fn clear_fields() -> Self {
        use ::re_types_core::Loggable as _;
        Self {
            voxel_indices: Some(SerializedComponentBatch::new(
                crate::components::VoxelIndex::arrow_empty(),
                Self::descriptor_voxel_indices(),
            )),
            voxel_size: Some(SerializedComponentBatch::new(
                crate::components::VoxelSize::arrow_empty(),
                Self::descriptor_voxel_size(),
            )),
            values: Some(SerializedComponentBatch::new(
                crate::components::VoxelValue::arrow_empty(),
                Self::descriptor_values(),
            )),
            colors: Some(SerializedComponentBatch::new(
                crate::components::Color::arrow_empty(),
                Self::descriptor_colors(),
            )),
            translation: Some(SerializedComponentBatch::new(
                crate::components::Translation3D::arrow_empty(),
                Self::descriptor_translation(),
            )),
            rotation_axis_angle: Some(SerializedComponentBatch::new(
                crate::components::RotationAxisAngle::arrow_empty(),
                Self::descriptor_rotation_axis_angle(),
            )),
            quaternion: Some(SerializedComponentBatch::new(
                crate::components::RotationQuat::arrow_empty(),
                Self::descriptor_quaternion(),
            )),
            opacity: Some(SerializedComponentBatch::new(
                crate::components::Opacity::arrow_empty(),
                Self::descriptor_opacity(),
            )),
            value_range: Some(SerializedComponentBatch::new(
                crate::components::ValueRange::arrow_empty(),
                Self::descriptor_value_range(),
            )),
            colormap: Some(SerializedComponentBatch::new(
                crate::components::Colormap::arrow_empty(),
                Self::descriptor_colormap(),
            )),
        }
    }

    /// Partitions the component data into multiple sub-batches.
    ///
    /// Specifically, this transforms the existing [`SerializedComponentBatch`]es data into [`SerializedComponentColumn`]s
    /// instead, via [`SerializedComponentBatch::partitioned`].
    ///
    /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
    ///
    /// The specified `lengths` must sum to the total length of the component batch.
    ///
    /// [`SerializedComponentColumn`]: [::re_types_core::SerializedComponentColumn]
    #[inline]
    pub fn columns<I>(
        self,
        _lengths: I,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>>
    where
        I: IntoIterator<Item = usize> + Clone,
    {
        let columns = [
            self.voxel_indices
                .map(|voxel_indices| voxel_indices.partitioned(_lengths.clone()))
                .transpose()?,
            self.voxel_size
                .map(|voxel_size| voxel_size.partitioned(_lengths.clone()))
                .transpose()?,
            self.values
                .map(|values| values.partitioned(_lengths.clone()))
                .transpose()?,
            self.colors
                .map(|colors| colors.partitioned(_lengths.clone()))
                .transpose()?,
            self.translation
                .map(|translation| translation.partitioned(_lengths.clone()))
                .transpose()?,
            self.rotation_axis_angle
                .map(|rotation_axis_angle| rotation_axis_angle.partitioned(_lengths.clone()))
                .transpose()?,
            self.quaternion
                .map(|quaternion| quaternion.partitioned(_lengths.clone()))
                .transpose()?,
            self.opacity
                .map(|opacity| opacity.partitioned(_lengths.clone()))
                .transpose()?,
            self.value_range
                .map(|value_range| value_range.partitioned(_lengths.clone()))
                .transpose()?,
            self.colormap
                .map(|colormap| colormap.partitioned(_lengths.clone()))
                .transpose()?,
        ];
        Ok(columns.into_iter().flatten())
    }

    /// Helper to partition the component data into unit-length sub-batches.
    ///
    /// This is semantically similar to calling [`Self::columns`] with `std::iter::take(1).repeat(n)`,
    /// where `n` is automatically guessed.
    #[inline]
    pub fn columns_of_unit_batches(
        self,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>> {
        let len_voxel_indices = self.voxel_indices.as_ref().map(|b| b.array.len());
        let len_voxel_size = self.voxel_size.as_ref().map(|b| b.array.len());
        let len_values = self.values.as_ref().map(|b| b.array.len());
        let len_colors = self.colors.as_ref().map(|b| b.array.len());
        let len_translation = self.translation.as_ref().map(|b| b.array.len());
        let len_rotation_axis_angle = self.rotation_axis_angle.as_ref().map(|b| b.array.len());
        let len_quaternion = self.quaternion.as_ref().map(|b| b.array.len());
        let len_opacity = self.opacity.as_ref().map(|b| b.array.len());
        let len_value_range = self.value_range.as_ref().map(|b| b.array.len());
        let len_colormap = self.colormap.as_ref().map(|b| b.array.len());
        let len = None
            .or(len_voxel_indices)
            .or(len_voxel_size)
            .or(len_values)
            .or(len_colors)
            .or(len_translation)
            .or(len_rotation_axis_angle)
            .or(len_quaternion)
            .or(len_opacity)
            .or(len_value_range)
            .or(len_colormap)
            .unwrap_or(0);
        self.columns(std::iter::repeat_n(1, len))
    }

    /// Indices of the voxels within the grid volume.
    #[inline]
    pub fn with_voxel_indices(
        mut self,
        voxel_indices: impl IntoIterator<Item = impl Into<crate::components::VoxelIndex>>,
    ) -> Self {
        self.voxel_indices = try_serialize_field(Self::descriptor_voxel_indices(), voxel_indices);
        self
    }

    /// The scene-unit dimensions of a single voxel cell.
    ///
    /// This defines the voxel size along the local grid X/Y/Z axes.
    /// Each dimension must be finite and positive.
    #[inline]
    pub fn with_voxel_size(mut self, voxel_size: impl Into<crate::components::VoxelSize>) -> Self {
        self.voxel_size = try_serialize_field(Self::descriptor_voxel_size(), [voxel_size]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::VoxelSize`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_voxel_size`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_voxel_size(
        mut self,
        voxel_size: impl IntoIterator<Item = impl Into<crate::components::VoxelSize>>,
    ) -> Self {
        self.voxel_size = try_serialize_field(Self::descriptor_voxel_size(), voxel_size);
        self
    }

    /// Optional scalar occupancy or value data for each voxel.
    ///
    /// If explicit colors are not provided, values are mapped through `colormap` and `value_range`.
    #[inline]
    pub fn with_values(
        mut self,
        values: impl IntoIterator<Item = impl Into<crate::components::VoxelValue>>,
    ) -> Self {
        self.values = try_serialize_field(Self::descriptor_values(), values);
        self
    }

    /// Optional colors for each voxel.
    ///
    /// If set, these colors take precedence over color-mapped scalar values.
    #[inline]
    pub fn with_colors(
        mut self,
        colors: impl IntoIterator<Item = impl Into<crate::components::Color>>,
    ) -> Self {
        self.colors = try_serialize_field(Self::descriptor_colors(), colors);
        self
    }

    /// Translation of the minimum corner of voxel `[0, 0, 0]`.
    ///
    /// Together with [`components::RotationAxisAngle`][crate::components::RotationAxisAngle] or [`components::RotationQuat`][crate::components::RotationQuat], this defines the pose of the
    /// grid relative to the map's parent coordinate frame.
    ///
    /// If not set, the minimum corner is placed at the origin of the map's parent coordinate frame.
    #[inline]
    pub fn with_translation(
        mut self,
        translation: impl Into<crate::components::Translation3D>,
    ) -> Self {
        self.translation = try_serialize_field(Self::descriptor_translation(), [translation]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::Translation3D`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_translation`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_translation(
        mut self,
        translation: impl IntoIterator<Item = impl Into<crate::components::Translation3D>>,
    ) -> Self {
        self.translation = try_serialize_field(Self::descriptor_translation(), translation);
        self
    }

    /// Rotation of the grid via axis + angle.
    ///
    /// Together with [`components::Translation3D`][crate::components::Translation3D], this defines the pose of the grid relative to the
    /// map's parent coordinate frame.
    ///
    /// Note: either this or [`components::RotationQuat`][crate::components::RotationQuat] can be set to specify the grid's rotation, but not both.
    /// If both this and [`components::RotationQuat`][crate::components::RotationQuat] are set, this is ignored in favor of the quaternion.
    #[inline]
    pub fn with_rotation_axis_angle(
        mut self,
        rotation_axis_angle: impl Into<crate::components::RotationAxisAngle>,
    ) -> Self {
        self.rotation_axis_angle = try_serialize_field(
            Self::descriptor_rotation_axis_angle(),
            [rotation_axis_angle],
        );
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::RotationAxisAngle`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_rotation_axis_angle`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_rotation_axis_angle(
        mut self,
        rotation_axis_angle: impl IntoIterator<Item = impl Into<crate::components::RotationAxisAngle>>,
    ) -> Self {
        self.rotation_axis_angle =
            try_serialize_field(Self::descriptor_rotation_axis_angle(), rotation_axis_angle);
        self
    }

    /// Rotation of the grid via quaternion.
    ///
    /// Together with [`components::Translation3D`][crate::components::Translation3D], this defines the pose of the grid relative to the
    /// map's parent coordinate frame.
    #[inline]
    pub fn with_quaternion(
        mut self,
        quaternion: impl Into<crate::components::RotationQuat>,
    ) -> Self {
        self.quaternion = try_serialize_field(Self::descriptor_quaternion(), [quaternion]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::RotationQuat`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_quaternion`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_quaternion(
        mut self,
        quaternion: impl IntoIterator<Item = impl Into<crate::components::RotationQuat>>,
    ) -> Self {
        self.quaternion = try_serialize_field(Self::descriptor_quaternion(), quaternion);
        self
    }

    /// Opacity of the voxels after color or colormap application.
    ///
    /// Defaults to 1.0 (fully opaque).
    #[inline]
    pub fn with_opacity(mut self, opacity: impl Into<crate::components::Opacity>) -> Self {
        self.opacity = try_serialize_field(Self::descriptor_opacity(), [opacity]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::Opacity`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_opacity`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_opacity(
        mut self,
        opacity: impl IntoIterator<Item = impl Into<crate::components::Opacity>>,
    ) -> Self {
        self.opacity = try_serialize_field(Self::descriptor_opacity(), opacity);
        self
    }

    /// Scalar value range for color-mapping.
    ///
    /// Defaults to `[0.0, 1.0]`.
    #[inline]
    pub fn with_value_range(
        mut self,
        value_range: impl Into<crate::components::ValueRange>,
    ) -> Self {
        self.value_range = try_serialize_field(Self::descriptor_value_range(), [value_range]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::ValueRange`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_value_range`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_value_range(
        mut self,
        value_range: impl IntoIterator<Item = impl Into<crate::components::ValueRange>>,
    ) -> Self {
        self.value_range = try_serialize_field(Self::descriptor_value_range(), value_range);
        self
    }

    /// Colormap to use when `values` are present and explicit `colors` are not provided.
    ///
    /// Defaults to Turbo.
    #[inline]
    pub fn with_colormap(mut self, colormap: impl Into<crate::components::Colormap>) -> Self {
        self.colormap = try_serialize_field(Self::descriptor_colormap(), [colormap]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::Colormap`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_colormap`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_colormap(
        mut self,
        colormap: impl IntoIterator<Item = impl Into<crate::components::Colormap>>,
    ) -> Self {
        self.colormap = try_serialize_field(Self::descriptor_colormap(), colormap);
        self
    }
}
