// NOTE: This file was autogenerated by re_types_builder; DO NOT EDIT.
// Based on "definitions/rerun/testing/components/fuzzy.fbs"

#pragma once

namespace rr {
    namespace components {
        struct AffixFuzzer3 {};
    } // namespace components
} // namespace rr
