#!/home/jleibs/rerun/.pixi/envs/default/bin/python3.11
# -*- coding: utf-8 -*-
import sys
from rerun_pixi_env import uvpy_shim_main
if __name__ == "__main__":
    if sys.argv[0].endswith("-script.pyw"):
        sys.argv[0] = sys.argv[0][:-11]
    elif sys.argv[0].endswith(".exe"):
        sys.argv[0] = sys.argv[0][:-4]
    sys.exit(uvpy_shim_main())
