direction: left

Rerun process: {
  Native Viewer: {
    Renderer
    Chunk Store
  }
  TCP Server
}

User process: {
  SDK
}

User process.SDK -> Rerun process.TCP Server
Rerun process.TCP Server -> Rerun process.Native Viewer.Chunk Store
