// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_types/definitions/rerun/components/opacity.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

#[doc(hidden)]
pub struct __OpacityMarker;

/// **Component**: Degree of transparency ranging from 0.0 (fully transparent) to 1.0 (fully opaque).
///
/// The final opacity value may be a result of multiplication with alpha values as specified by other color sources.
/// Unless otherwise specified, the default value is 1.
pub type Opacity = crate::WrapperComponent<crate::datatypes::Float32, __OpacityMarker>;

#[allow(non_snake_case)]
#[inline]
pub const fn Opacity(v: crate::datatypes::Float32) -> Opacity {
    crate::WrapperComponent::<crate::datatypes::Float32, __OpacityMarker>(
        v,
        std::marker::PhantomData,
    )
}

impl ::re_types_core::Component for Opacity {
    #[inline]
    fn name() -> ComponentType {
        "rerun.components.Opacity".into()
    }
}

impl<T: Into<crate::datatypes::Float32>> From<T> for Opacity {
    fn from(v: T) -> Self {
        Opacity(v.into())
    }
}
