/// Implements the codegen pass.
pub trait CodeGenerator {
    /// Generates user-facing code from [`crate::Objects`].
    ///
    /// Returns the paths of all generated files.
    fn quote(
        &mut self,
        objs: &crate::Objects,
        arrow_registry: &crate::ArrowRegistry,
    ) -> Vec<std::path::PathBuf>;
}

// ---

pub const AUTOGEN_WARNING: &str =
    "NOTE: This file was autogenerated by re_types_builder; DO NOT EDIT.";

pub const RERUN_ATTR_COMPONENT_REQUIRED: &str = "rerun.attr.component_required";
pub const RERUN_ATTR_COMPONENT_RECOMMENDED: &str = "rerun.attr.component_recommended";
pub const RERUN_ATTR_COMPONENT_OPTIONAL: &str = "rerun.attr.component_optional";

// ---

mod common;
use self::common::quote_doc_from_docs;

mod python;
mod rust;

pub use self::python::PythonCodeGenerator;
pub use self::rust::RustCodeGenerator;
