"""Constants for the names of the visualizers."""

from __future__ import annotations

BarChar = "BarChart"
Arrows2D = "Arrows2D"
Arrows3D = "Arrows3D"
Asset3D = "Asset3D"
Boxes2D = "Boxes2D"
Boxes3D = "Boxes3D"
Cameras = "Cameras"
DepthImage = "DepthImage"
Image = "Image"
Lines2D = "Lines2D"
Lines3D = "Lines3D"
Mesh3D = "Mesh3D"
Points2D = "Points2D"
Points3D = "Points3D"
Transform3DArrows = "Transform3DArrows"
Tensor = "Tensor"
TextDocument = "TextDocument"
TextLog = "TextLog"
SegmentationImage = "SegmentationImage"
SeriesLine = "SeriesLine"
SeriesPoint = "SeriesPoint"
