name: Cargo Shear

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize]

jobs:
  cargo-shear:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Shear
        run: |
          cargo binstall --no-confirm cargo-shear
          cargo shear
