# Checks that all checkboxes in a PR are checked

name: Pull Request Checkboxes

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited

concurrency:
  group: ${{ github.event.pull_request.number }}-pr-checkboxes
  cancel-in-progress: true

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

permissions:
  contents: "read"
  pull-requests: "read"

jobs:
  pr-checkboxes:
    name: Check PR checkboxes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          pixi-version: v0.71.3

      - name: Check PR checkboxes
        run: |
          pixi run ./scripts/ci/check_pr_checkboxes.py \
            --github-token ${{ secrets.GITHUB_TOKEN }} \
            --github-repository ${{ github.repository }} \
            --pr-number ${{ github.event.pull_request.number }}
