# https://github.com/marketplace/actions/require-labels
# Check for existence of labels
# See all our labels at https://github.com/rerun-io/rerun/issues/labels

name: Pull Request Labels

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

# No permissions needed here
# permissions:

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for a "do-not-merge" label
        uses: mheap/github-action-required-labels@bddc3b922a9fc4398a96b7da18ec5a1ce7d75b93 # v3.0.1
        with:
          mode: exactly
          count: 0
          labels: "do-not-merge"

      - name: Require a changelog category label
        uses: mheap/github-action-required-labels@bddc3b922a9fc4398a96b7da18ec5a1ce7d75b93 # v3.0.1
        with:
          mode: minimum
          count: 1
          labels: "exclude from changelog, 🪳 bug, 📉 performance, include in changelog"

      - name: Require at least one label
        uses: mheap/github-action-required-labels@bddc3b922a9fc4398a96b7da18ec5a1ce7d75b93 # v3.0.1
        with:
          mode: minimum
          count: 1
          #NOLINT_START: skip lint rules on labels (dataplatform)
          labels: "📊 analytics, 🟦 blueprint, 🪳 bug, CLI, codegen/idl, 🧑‍💻 dev experience, dependencies, 📖 documentation, 💬 discussion, examples, exclude from changelog, 🪵 Log & send APIs, 📉 performance, sdk-python, sdk-cpp, sdk-rust, ⛃ re_datastore, 🔍 re_query, 📺 re_viewer, 🔺 re_renderer, 🚜 refactor, ⛴ release, 🔨 testing, ui, 🕸️ web, 🧢 MCAP, OSS-server, dataplatform"
          #NOLINT_END

  wasm-bindgen-check:
    name: Check wasm-bindgen version
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0

      - uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          pixi-version: v0.71.3

      - name: Get current wasm-bindgen version
        id: current-version
        run: |
          version=$(pixi run taplo get -f crates/viewer/re_viewer/Cargo.toml "target.*.dependencies.wasm-bindgen")
          echo "current_version=$version" >> $GITHUB_OUTPUT

      - name: Get previous wasm-bindgen version
        id: previous-version
        run: |
          prev_ref=$(git rev-parse --abbrev-ref HEAD)
          git checkout main

          version=$(pixi run taplo get -f crates/viewer/re_viewer/Cargo.toml "target.*.dependencies.wasm-bindgen")
          echo "previous_version=$version" >> $GITHUB_OUTPUT

          git checkout $prev_ref

      - name: Require label if versions changed
        if: ${{ steps.current-version.outputs.current_version != steps.previous-version.outputs.previous_version }}
        uses: mheap/github-action-required-labels@bddc3b922a9fc4398a96b7da18ec5a1ce7d75b93 # v3.0.1
        with:
          mode: exactly
          count: 1
          labels: "wasm-bindgen version update"
