// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_types/definitions/rerun/datatypes/text_log_column.fbs".

#pragma once

#include "../result.hpp"
#include "utf8.hpp"

#include <cassert>
#include <cstdint>
#include <cstring>
#include <memory>
#include <new>
#include <utility>

namespace arrow {
    class Array;
    class DataType;
    class DenseUnionBuilder;
} // namespace arrow

namespace rerun::datatypes {
    namespace detail {
        /// \private
        enum class TextLogColumnKindTag : uint8_t {
            /// Having a special empty state makes it possible to implement move-semantics. We need to be able to leave the object in a state which we can run the destructor on.
            None = 0,
            Timeline,
            EntityPath,
            LogLevel,
            Body,
        };

        /// \private
        union TextLogColumnKindData {
            /// A specific timeline's column.
            rerun::datatypes::Utf8 timeline;

            TextLogColumnKindData() {
                std::memset(reinterpret_cast<void*>(this), 0, sizeof(TextLogColumnKindData));
            }

            ~TextLogColumnKindData() {}

            void swap(TextLogColumnKindData& other) noexcept {
                // This bitwise swap would fail for self-referential types, but we don't have any of those.
                char temp[sizeof(TextLogColumnKindData)];
                void* otherbytes = reinterpret_cast<void*>(&other);
                void* thisbytes = reinterpret_cast<void*>(this);
                std::memcpy(temp, thisbytes, sizeof(TextLogColumnKindData));
                std::memcpy(thisbytes, otherbytes, sizeof(TextLogColumnKindData));
                std::memcpy(otherbytes, temp, sizeof(TextLogColumnKindData));
            }
        };
    } // namespace detail

    /// **Datatype**: A text log column kind.
    struct TextLogColumnKind {
        TextLogColumnKind() : _tag(detail::TextLogColumnKindTag::None) {}

        /// Copy constructor
        TextLogColumnKind(const TextLogColumnKind& other) : _tag(other._tag) {
            switch (other._tag) {
                case detail::TextLogColumnKindTag::Timeline: {
                    using TypeAlias = rerun::datatypes::Utf8;
                    new (&_data.timeline) TypeAlias(other._data.timeline);
                } break;
                case detail::TextLogColumnKindTag::EntityPath:
                case detail::TextLogColumnKindTag::LogLevel:
                case detail::TextLogColumnKindTag::Body: {
                    const void* otherbytes = reinterpret_cast<const void*>(&other._data);
                    void* thisbytes = reinterpret_cast<void*>(&this->_data);
                    std::memcpy(thisbytes, otherbytes, sizeof(detail::TextLogColumnKindData));
                } break;
                case detail::TextLogColumnKindTag::None: {
                } break;
                default:
                    assert(false && "unreachable");
            }
        }

        TextLogColumnKind& operator=(const TextLogColumnKind& other) noexcept {
            TextLogColumnKind tmp(other);
            this->swap(tmp);
            return *this;
        }

        TextLogColumnKind(TextLogColumnKind&& other) noexcept : TextLogColumnKind() {
            this->swap(other);
        }

        TextLogColumnKind& operator=(TextLogColumnKind&& other) noexcept {
            this->swap(other);
            return *this;
        }

        ~TextLogColumnKind() {
            switch (this->_tag) {
                case detail::TextLogColumnKindTag::None: {
                    // Nothing to destroy
                } break;
                case detail::TextLogColumnKindTag::Timeline: {
                    using TypeAlias = rerun::datatypes::Utf8;
                    _data.timeline.~TypeAlias();
                } break;
                case detail::TextLogColumnKindTag::EntityPath: {
                    // has a trivial destructor
                } break;
                case detail::TextLogColumnKindTag::LogLevel: {
                    // has a trivial destructor
                } break;
                case detail::TextLogColumnKindTag::Body: {
                    // has a trivial destructor
                } break;
                default:
                    assert(false && "unreachable");
            }
        }

        void swap(TextLogColumnKind& other) noexcept {
            std::swap(this->_tag, other._tag);
            this->_data.swap(other._data);
        }

        /// A specific timeline's column.
        static TextLogColumnKind timeline(rerun::datatypes::Utf8 timeline) {
            TextLogColumnKind self;
            self._tag = detail::TextLogColumnKindTag::Timeline;
            new (&self._data.timeline) rerun::datatypes::Utf8(std::move(timeline));
            return self;
        }

        /// Column for which entity path this was logged to.
        static TextLogColumnKind entity_path() {
            TextLogColumnKind self;
            self._tag = detail::TextLogColumnKindTag::EntityPath;
            return self;
        }

        /// Column for log-level.
        static TextLogColumnKind log_level() {
            TextLogColumnKind self;
            self._tag = detail::TextLogColumnKindTag::LogLevel;
            return self;
        }

        /// The text message the log has.
        static TextLogColumnKind body() {
            TextLogColumnKind self;
            self._tag = detail::TextLogColumnKindTag::Body;
            return self;
        }

        /// Return a pointer to timeline if the union is in that state, otherwise `nullptr`.
        const rerun::datatypes::Utf8* get_timeline() const {
            if (_tag == detail::TextLogColumnKindTag::Timeline) {
                return &_data.timeline;
            } else {
                return nullptr;
            }
        }

        /// Returns true if the union is in the entity_path state.
        bool is_entity_path() const {
            return _tag == detail::TextLogColumnKindTag::EntityPath;
        }

        /// Returns true if the union is in the log_level state.
        bool is_log_level() const {
            return _tag == detail::TextLogColumnKindTag::LogLevel;
        }

        /// Returns true if the union is in the body state.
        bool is_body() const {
            return _tag == detail::TextLogColumnKindTag::Body;
        }

        /// \private
        const detail::TextLogColumnKindData& get_union_data() const {
            return _data;
        }

        /// \private
        detail::TextLogColumnKindTag get_union_tag() const {
            return _tag;
        }

      private:
        detail::TextLogColumnKindTag _tag;
        detail::TextLogColumnKindData _data;
    };
} // namespace rerun::datatypes

namespace rerun {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<datatypes::TextLogColumnKind> {
        static constexpr std::string_view ComponentType = "rerun.datatypes.TextLogColumnKind";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype();

        /// Serializes an array of `rerun::datatypes::TextLogColumnKind` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const datatypes::TextLogColumnKind* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static rerun::Error fill_arrow_array_builder(
            arrow::DenseUnionBuilder* builder, const datatypes::TextLogColumnKind* elements,
            size_t num_elements
        );
    };
} // namespace rerun
