// DO NOT EDIT! This file was auto-generated by crates/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/re_types/definitions/rerun/datatypes/uvec3d.fbs".

#pragma once

#include "../result.hpp"

#include <array>
#include <cstdint>
#include <memory>

namespace arrow {
    class DataType;
    class FixedSizeListBuilder;
} // namespace arrow

namespace rerun::datatypes {
    /// **Datatype**: A uint32 vector in 3D space.
    struct UVec3D {
        std::array<uint32_t, 3> xyz;

      public:
        UVec3D() = default;

        UVec3D(std::array<uint32_t, 3> xyz_) : xyz(xyz_) {}

        UVec3D& operator=(std::array<uint32_t, 3> xyz_) {
            xyz = xyz_;
            return *this;
        }

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype();

        /// Fills an arrow array builder with an array of this type.
        static rerun::Error fill_arrow_array_builder(
            arrow::FixedSizeListBuilder* builder, const UVec3D* elements, size_t num_elements
        );
    };
} // namespace rerun::datatypes
